pr:
- develop
    
pool: 'agent-name'
    
steps:
- task: PowerShell@2
    inputs:
    filePath: 'tests\Invoke-Test.ps1'
    failOnStderr: true
    workingDirectory: 'tests'
- task: PublishTestResults@2
    inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**\tests\*.xml'
    failTaskOnFailedTests: true
